platform: x64

clone_folder: c:\gopath\src\github.com\sacloud\usacloud

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;C:\go110\bin;%PATH%
  - go version
  - go env

init:
  - git config --global core.autocrlf false

test_script:
  - go test -v ./... -timeout=30s -parallel=4

build: off
deploy: off
