site_name: Usacloudドキュメント
site_url: https://sacloud.github.io/usacloud/
site_description: Usacloud日本語ドキュメント
site_author: '@yamamoto-febc'
repo_url: https://github.com/sacloud/usacloud
repo_name: usacloud
copyright: Copyright (C) 2017 Kazumichi Yamamoto.
google_analytics: ['UA-63739336-4','auto']
theme: readthedocs
extra_css:
  - css/extra.css
pages:
  - ホーム: index.md
  - usacloud 導入ガイド: start_guide.md
  - usacloud コマンド:
    - 基本的な使い方: basic_usage.md
    - サーバの作成: usage_server_build.md
    - 電源操作: usage_server_power.md
    - 接続(SSH/VNC): usage_server_connect.md
    - ファイル送受信(SCP): usage_server_scp.md
    - オブジェクトストレージの操作: usage_ojs.md
    - アーカイブのダウンロード: usage_download.md
    - ISOイメージのアップロード: usage_upload.md
    - 監視/モニタリング: usage_monitoring.md
  - コマンドリファレンス:
    - コンピューティング:
      - server: commands/server.md
    - ストレージ:
      - archive: commands/archive.md
      - auto-backup: commands/auto_backup.md
      - disk: commands/disk.md
      - iso-image: commands/iso_image.md
      - object-storage: commands/object_storage.md
    - ネットワーキング:
      - bridge: commands/bridge.md
      - internet: commands/internet.md
      - packet-filter: commands/packet_filter.md
      - switch: commands/switch.md
      - interface: commands/interface.md
    - アプライアンス:
      - database: commands/database.md
      - load-balancer: commands/load_balancer.md
      - vpc-router: commands/vpc_router.md
    - 共通サービスアイテム:
      - dns: commands/dns.md
      - gslb: commands/gslb.md
      - simple-monitor: commands/simple_monitor.md
    - 共通アイテム:
      - license: commands/license.md
      - icon: commands/icon.md
      - ssh-key: commands/ssh_key.md
      - startup-script: commands/startup_script.md
    - 請求:
      - bill: commands/bill.md
    - サービス:
      - web-accel: commands/webaccel.md
    - 製品/プラン/情報:
      - price: commands/price.md
      - product-disk: commands/product_disk.md
      - product-internet: commands/product_internet.md
      - product-license: commands/product_license.md
      - product-server: commands/product_server.md
      - region: commands/region.md
      - zone: commands/zone.md
    - その他:
      - confg: commands/config.md
