# from https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images#publishing-images-to-github-packages
name: Publish Docker image
on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry(latest)
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/sacloud/usacloud
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          tags: ${{ steps.docker_meta.outputs.tags }},ghcr.io/sacloud/usacloud:latest
          push: true
